/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import EscolaSys.Model.Pessoa;
import javax.swing.*;
import EscolaSys.Model.BancoDeDados;
import EscolaSys.View.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dev01
 */
public class CadastrarMain extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarAluno
     */
    
    protected AlunoView aluno = new AlunoView();
    protected ProfessorView professor = new ProfessorView();
    protected RecepcionistaView recepcionista = new RecepcionistaView();
    
    public CadastrarMain() {
        initComponents();
       panel_aluno.setVisible(false);
       panel_professor.setVisible(false);
       panel_recepcionista.setVisible(false);
       
    }
    
    public void type_exec(int type)
    {
       
       switch(type)
       {
           case 1:
              panel_aluno.setVisible(true);
              break;
           case 2:
              panel_professor.setVisible(true);
              break;
           default:
              panel_recepcionista.setVisible(true);
              break;
               
       }
       this.setExtendedState(6);
       this.setVisible(true);
    }
    
     private void LimparCampos(){
    
        campo_nome.setText("");
        campo_dtNasc.setText("");
        campo_cpf.setText("");
        campo_rg.setText("");
        campo_telefone.setText("");
        
        campo_logradouro.setText("");
        campo_numero.setText("");
        campo_complemento.setText("");
        campo_cep.setText("");
        campo_bairro.setText("");
        campo_cidade.setText("");
        campo_uf.setText("");
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campo_nome = new javax.swing.JTextField();
        campo_dtNasc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campo_cpf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campo_rg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campo_telefone = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        campo_logradouro = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        campo_numero = new javax.swing.JTextField();
        campo_complemento = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        campo_cep = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        campo_bairro = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        campo_cidade = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        campo_uf = new javax.swing.JTextField();
        panel_aluno = new javax.swing.JPanel();
        label_tipo_cadastro = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        campo_matricula = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        campo_celular = new javax.swing.JTextField();
        panel_professor = new javax.swing.JPanel();
        label_tipo_cadastro2 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        campo_lattes = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        campo_email = new javax.swing.JTextField();
        campo_formacao = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        campo_especialidade = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        campo_tipo_professor = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        panel_recepcionista = new javax.swing.JPanel();
        label_tipo_cadastro3 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        campo_dep_recep = new javax.swing.JTextField();
        btn_save_cadas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Escola Sys - XYZ Tecnologia");

        btn_back.setText("Voltar");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(104, 104, 104))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_back)
                    .addComponent(jLabel1))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Pessoa");
        jLabel2.setToolTipText("");

        jLabel3.setFont(jLabel3.getFont());
        jLabel3.setText("Nome");

        campo_nome.setToolTipText("");

        campo_dtNasc.setToolTipText("");

        jLabel4.setFont(jLabel4.getFont());
        jLabel4.setText("Data de Nascimento");

        campo_cpf.setToolTipText("");

        jLabel5.setFont(jLabel5.getFont());
        jLabel5.setText("CPF");

        jLabel6.setFont(jLabel6.getFont());
        jLabel6.setText("RG");

        campo_rg.setToolTipText("");

        jLabel7.setFont(jLabel7.getFont());
        jLabel7.setText("Telefone");

        campo_telefone.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(campo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(campo_dtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(campo_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(campo_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7)
                    .addComponent(campo_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_dtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Endereço");
        jLabel17.setToolTipText("");

        jLabel23.setFont(jLabel23.getFont());
        jLabel23.setText("Endereço");

        campo_logradouro.setToolTipText("");

        jLabel24.setFont(jLabel24.getFont());
        jLabel24.setText("Número");

        campo_numero.setToolTipText("");

        campo_complemento.setToolTipText("");

        jLabel25.setFont(jLabel25.getFont());
        jLabel25.setText("Complemento");

        jLabel26.setFont(jLabel26.getFont());
        jLabel26.setText("CEP");

        campo_cep.setToolTipText("");

        jLabel27.setFont(jLabel27.getFont());
        jLabel27.setText("Bairro");

        campo_bairro.setToolTipText("");

        jLabel28.setFont(jLabel28.getFont());
        jLabel28.setText("Cidade");

        campo_cidade.setToolTipText("");

        jLabel29.setFont(jLabel29.getFont());
        jLabel29.setText("UF");

        campo_uf.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(campo_logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(campo_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(campo_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(campo_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(campo_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(campo_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(campo_uf, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        panel_aluno.setBackground(new java.awt.Color(255, 255, 255));

        label_tipo_cadastro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_tipo_cadastro.setText("Aluno");
        label_tipo_cadastro.setToolTipText("");

        jLabel30.setFont(jLabel30.getFont());
        jLabel30.setText("Matrícula");

        campo_matricula.setToolTipText("");

        jLabel31.setFont(jLabel31.getFont());
        jLabel31.setText("Celular");

        campo_celular.setToolTipText("");

        javax.swing.GroupLayout panel_alunoLayout = new javax.swing.GroupLayout(panel_aluno);
        panel_aluno.setLayout(panel_alunoLayout);
        panel_alunoLayout.setHorizontalGroup(
            panel_alunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_alunoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panel_alunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_tipo_cadastro)
                    .addGroup(panel_alunoLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(128, 128, 128)
                        .addComponent(jLabel31))
                    .addGroup(panel_alunoLayout.createSequentialGroup()
                        .addComponent(campo_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(campo_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panel_alunoLayout.setVerticalGroup(
            panel_alunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_alunoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(label_tipo_cadastro)
                .addGap(6, 6, 6)
                .addGroup(panel_alunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGap(6, 6, 6)
                .addGroup(panel_alunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_professor.setBackground(new java.awt.Color(255, 255, 255));

        label_tipo_cadastro2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_tipo_cadastro2.setText("Professor");
        label_tipo_cadastro2.setToolTipText("");

        jLabel34.setFont(jLabel34.getFont());
        jLabel34.setText("Lattes");

        campo_lattes.setToolTipText("");

        jLabel35.setFont(jLabel35.getFont());
        jLabel35.setText("Email");

        campo_email.setToolTipText("");

        campo_formacao.setToolTipText("");

        jLabel36.setFont(jLabel36.getFont());
        jLabel36.setText("Formação");

        campo_especialidade.setToolTipText("");

        jLabel37.setFont(jLabel37.getFont());
        jLabel37.setText("Especialidade");

        campo_tipo_professor.setToolTipText("");
        campo_tipo_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_tipo_professorActionPerformed(evt);
            }
        });

        jLabel38.setFont(jLabel38.getFont());
        jLabel38.setText("Tipo");

        javax.swing.GroupLayout panel_professorLayout = new javax.swing.GroupLayout(panel_professor);
        panel_professor.setLayout(panel_professorLayout);
        panel_professorLayout.setHorizontalGroup(
            panel_professorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_professorLayout.createSequentialGroup()
                .addGroup(panel_professorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_professorLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(label_tipo_cadastro2))
                    .addGroup(panel_professorLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel34)
                        .addGap(147, 147, 147)
                        .addComponent(jLabel35)
                        .addGap(148, 148, 148)
                        .addComponent(jLabel36)
                        .addGap(128, 128, 128)
                        .addComponent(jLabel37))
                    .addGroup(panel_professorLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(campo_lattes, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(campo_email, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(campo_formacao, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(campo_especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_professorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_professorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(campo_tipo_professor, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_professorLayout.setVerticalGroup(
            panel_professorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_professorLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(label_tipo_cadastro2)
                .addGap(1, 1, 1)
                .addGroup(panel_professorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addGroup(panel_professorLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(panel_professorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35))))
                .addGap(5, 5, 5)
                .addGroup(panel_professorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_formacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_professorLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(panel_professorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo_lattes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addGap(0, 0, 0)
                .addComponent(campo_tipo_professor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_recepcionista.setBackground(new java.awt.Color(255, 255, 255));

        label_tipo_cadastro3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_tipo_cadastro3.setText("Recepcionista");
        label_tipo_cadastro3.setToolTipText("");

        jLabel39.setFont(jLabel39.getFont());
        jLabel39.setText("Departamento");

        campo_dep_recep.setToolTipText("");
        campo_dep_recep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_dep_recepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_recepcionistaLayout = new javax.swing.GroupLayout(panel_recepcionista);
        panel_recepcionista.setLayout(panel_recepcionistaLayout);
        panel_recepcionistaLayout.setHorizontalGroup(
            panel_recepcionistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_recepcionistaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panel_recepcionistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_tipo_cadastro3)
                    .addComponent(jLabel39)
                    .addComponent(campo_dep_recep, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panel_recepcionistaLayout.setVerticalGroup(
            panel_recepcionistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_recepcionistaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(label_tipo_cadastro3)
                .addGap(6, 6, 6)
                .addComponent(jLabel39)
                .addGap(6, 6, 6)
                .addComponent(campo_dep_recep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_save_cadas.setText("Salvar");
        btn_save_cadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_cadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_aluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_recepcionista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_save_cadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_professor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_professor, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_save_cadas)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
       new Escola().RodarTelaInicial();
       dispose();
    }//GEN-LAST:event_btn_backActionPerformed
    
    
    private void btn_save_cadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_cadasActionPerformed
       boolean trava = false;
       Pessoa pessoa = new Pessoa();
       
       // Pessoa
       String nome, dtNasc, cpf, rg, telefone;
       
       nome = campo_nome.getText();
       dtNasc = campo_dtNasc.getText();
       cpf = campo_cpf.getText();
       rg = campo_rg.getText();
       telefone = campo_telefone.getText();
       
       // Endereço
       String logradouro, numero, complemento, cep, bairro, cidade, uf;
       
       logradouro = campo_logradouro.getText();
       numero = campo_numero.getText();
       complemento = campo_complemento.getText();
       cep = campo_cep.getText();
       bairro = campo_bairro.getText();
       cidade = campo_cidade.getText();
       uf = campo_uf.getText();
       
       try
       {
           String[] dados_endereco = new String[20];
            //endereco.CadastrarEndereco(logradouro, numero, complemento, cep, 
               //bairro, cidade, uf);
            dados_endereco[0] = logradouro;
            dados_endereco[1] = numero;
            dados_endereco[2] = complemento;
            dados_endereco[3] = cep;
            dados_endereco[4] = bairro;
            dados_endereco[5] = cidade;
            dados_endereco[6] = uf;
            
            pessoa.cadastrarPessoa(nome, dtNasc, cpf, rg, telefone, dados_endereco);
            trava = true;

       } catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e.getMessage());
           System.out.println(e.getMessage());
       }
       
       if(trava)
       {
        if(panel_aluno.isVisible())
        {
            String matricula, celular;

            matricula = campo_matricula.getText();
            celular = campo_celular.getText();

            try
            {
                aluno.setMatricula(matricula);
                aluno.setCelular(celular);
                aluno.cadastrarAluno(pessoa.exibirPessoa());
                
                campo_matricula.setText("");
                campo_celular.setText("");
                
                LimparCampos();
            } catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
        else if(panel_professor.isVisible())
        {
            String lattes, email, formacao, especialidade, tipo;

            lattes = campo_lattes.getText();
            email = campo_email.getText();
            formacao = campo_formacao.getText();
            especialidade = campo_especialidade.getText();
            tipo = campo_tipo_professor.getText();
        }
        else
        {
            String departamento = campo_dep_recep.getText();
        }
       }

       
    }//GEN-LAST:event_btn_save_cadasActionPerformed

    private void campo_tipo_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_tipo_professorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_tipo_professorActionPerformed

    private void campo_dep_recepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_dep_recepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_dep_recepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new Escola().RodarTelaCadastroMain();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_save_cadas;
    private javax.swing.JTextField campo_bairro;
    private javax.swing.JTextField campo_celular;
    private javax.swing.JTextField campo_cep;
    private javax.swing.JTextField campo_cidade;
    private javax.swing.JTextField campo_complemento;
    private javax.swing.JTextField campo_cpf;
    private javax.swing.JTextField campo_dep_recep;
    private javax.swing.JTextField campo_dtNasc;
    private javax.swing.JTextField campo_email;
    private javax.swing.JTextField campo_especialidade;
    private javax.swing.JTextField campo_formacao;
    private javax.swing.JTextField campo_lattes;
    private javax.swing.JTextField campo_logradouro;
    private javax.swing.JTextField campo_matricula;
    private javax.swing.JTextField campo_nome;
    private javax.swing.JTextField campo_numero;
    private javax.swing.JTextField campo_rg;
    private javax.swing.JTextField campo_telefone;
    private javax.swing.JTextField campo_tipo_professor;
    private javax.swing.JTextField campo_uf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label_tipo_cadastro;
    private javax.swing.JLabel label_tipo_cadastro2;
    private javax.swing.JLabel label_tipo_cadastro3;
    private javax.swing.JPanel panel_aluno;
    private javax.swing.JPanel panel_professor;
    private javax.swing.JPanel panel_recepcionista;
    // End of variables declaration//GEN-END:variables

}
